export enum UserType {
    UNDEFINED = 'UNDEFINED',
    ADMINISTRATOR = 'ADMINISTRATOR',
    COMPANY_MANAGER = 'COMPANY_MANAGER',
    COMPANY_WORKER = 'COMPANY_WORKER',
    EDITOR = 'EDITOR',
    DONOR = 'DONOR'
}
