version: '3.2'

services:
  hlf-explorer-api:
    image: hlf-explorer-api
    env_file:
      - ./../../docker/explorer/backend/api/.env
    volumes:
      - ./../../docker/explorer/backend/api/data:/application/build/data
    ports:
      - "3000:3000"
    depends_on:
      - hlf-explorer-db
    networks:
      - default
      - ledger

  hlf-explorer-db:
    image: postgres:11.4-alpine
    env_file:
      - ./../../docker/explorer/backend/database/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    networks:
      - default
      - ledger

volumes:
  pg_data:

networks:
  ledger:
    external:
      name: ledger_network
