on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Building HLF Explorer Backend
        run: |
          docker build -f docker/explorer/backend/api/Dockerfile -t karma-charity-platform/hlf-explorer-api .
